.\" mkapfs.8 - manpage for mkapfs
.\"
.\" Copyright (C) 2019 Ernesto A. Fernández <ernesto.mnd.fernandez@gmail.com>
.\"
.TH mkapfs 8 "May 2019" "apfsprogs 0.1"
.SH NAME
mkapfs \- create an APFS filesystem
.SH SYNOPSIS
.B mkapfs
[\-v]
.I device
.RI [ blocks ]
.SH DESCRIPTION
.B mkapfs
is an experimental tool to create an APFS filesystem on the given
.IR device .
The number of blocks in the container can be specified in
.IR blocks ,
otherwise the whole disk is used.
.SH OPTIONS
.TP
.B \-v
Print the version number of
.B mkapfs
and exit.
.SH REPORTING BUGS
Please submit any issues that you find to the project's mailing list at
<linux-apfs@googlegroups.com>.
.SH AUTHOR
Written by Ernesto A. Fernández <ernesto.mnd.fernandez@gmail.com>.
.SH SEE ALSO
.BR apfsck (8)
